version: '2'

services:
  # mongo database
  db:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    command: --smallfiles --storageEngine wiredTiger

  # redis broker or cache
  broker:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: --appendonly yes

  # celery service
  worker:
    image: flask-scaffolding
    volumes:
      - ./src:/code
      - ./logs:/var/log
    env_file:
      local.env
    command: >
      /bin/ash -c "
        while ! nc -z broker 6379;
        do
          echo sleeping for broker;
          sleep 1;
        done;
        while ! nc -z db 27017;
        do
          echo sleeping for database;
          sleep 1;
        done;

        su -m celery -c 'celery -A app.celery worker --loglevel=info'
      "
    depends_on:
      - broker
      - web
      - db

  # web service for flask application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-scaffolding
    env_file:
      local.env
    command: >
      /bin/ash -c "
        while ! nc -z broker 6379;
        do
          echo sleeping for broker;
          sleep 1;
        done;

        while ! nc -z db 27017;
        do
          echo sleeping for database;
          sleep 1;
        done;

        gunicorn --bind=0.0.0.0:5000 -w 2 app
      "
    volumes:
      - ./src/:/code
      - ./logs:/var/log
    ports:
      - "8400:5000"
    depends_on:
      - broker
      - db
