# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scaffolding.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scaffolding.proto',
  package='scaffolding',
  syntax='proto3',
  serialized_pb=_b('\n\x11scaffolding.proto\x12\x0bscaffolding\"\x8a\x01\n\x0bScaffolding\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x43\n\x10scaffolding_type\x18\x04 \x01(\x0e\x32).scaffolding.Scaffolding.scaffolding_enum\"(\n\x10scaffolding_enum\x12\t\n\x05\x65num0\x10\x00\x12\t\n\x05\x65num1\x10\x01\x62\x06proto3')
)



_SCAFFOLDING_SCAFFOLDING_ENUM = _descriptor.EnumDescriptor(
  name='scaffolding_enum',
  full_name='scaffolding.Scaffolding.scaffolding_enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='enum0', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='enum1', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=133,
  serialized_end=173,
)
_sym_db.RegisterEnumDescriptor(_SCAFFOLDING_SCAFFOLDING_ENUM)


_SCAFFOLDING = _descriptor.Descriptor(
  name='Scaffolding',
  full_name='scaffolding.Scaffolding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='scaffolding.Scaffolding.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scaffolding_type', full_name='scaffolding.Scaffolding.scaffolding_type', index=1,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SCAFFOLDING_SCAFFOLDING_ENUM,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=173,
)

_SCAFFOLDING.fields_by_name['scaffolding_type'].enum_type = _SCAFFOLDING_SCAFFOLDING_ENUM
_SCAFFOLDING_SCAFFOLDING_ENUM.containing_type = _SCAFFOLDING
DESCRIPTOR.message_types_by_name['Scaffolding'] = _SCAFFOLDING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Scaffolding = _reflection.GeneratedProtocolMessageType('Scaffolding', (_message.Message,), dict(
  DESCRIPTOR = _SCAFFOLDING,
  __module__ = 'scaffolding_pb2'
  # @@protoc_insertion_point(class_scope:scaffolding.Scaffolding)
  ))
_sym_db.RegisterMessage(Scaffolding)


# @@protoc_insertion_point(module_scope)
